# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import execute_script_pb2 as execute__script__pb2


class ExecuterStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteScript = channel.unary_stream(
                '/executescript.Executer/ExecuteScript',
                request_serializer=execute__script__pb2.ScriptChoice.SerializeToString,
                response_deserializer=execute__script__pb2.ScriptResult.FromString,
                )


class ExecuterServicer(object):
    """The greeting service definition.
    """

    def ExecuteScript(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExecuterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteScript': grpc.unary_stream_rpc_method_handler(
                    servicer.ExecuteScript,
                    request_deserializer=execute__script__pb2.ScriptChoice.FromString,
                    response_serializer=execute__script__pb2.ScriptResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'executescript.Executer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Executer(object):
    """The greeting service definition.
    """

    @staticmethod
    def ExecuteScript(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/executescript.Executer/ExecuteScript',
            execute__script__pb2.ScriptChoice.SerializeToString,
            execute__script__pb2.ScriptResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
